"""initial schema: AGE property graph + audit log + embedding tables

Revision ID: 0001
Revises:
Create Date: 2026-08-20

Hand-written raw SQL/Cypher, not autogenerated (see migrations/env.py). Node
and edge shapes match docs/designs/echo-memory-design.md's Concrete Schema.

Vector storage note (not yet written down elsewhere): pgvector's HNSW index
needs a native `vector` column, which an AGE property (agtype) can't be. So
embeddings live in two plain tables (fact_embedding, node_embedding) keyed by
the AGE graphid they describe, joined back to the graph only at RRF-fusion
time. Full-text search doesn't have this problem: a GIN expression index
works directly against the AGE edge table's `fact` property, so that stays
in the graph. Everything else (nodes, edges, tenancy/temporal filtering)
follows PR0a's spike: explicit per-property CREATE (not `SET n = row`,
unsupported in AGE 1.5.0 from a runtime map) and agtype key literals cast
explicitly (`properties ->> '"key"'::agtype`, not a bare SQL string).

EMBEDDING_DIM=1536 is a placeholder (OpenAI text-embedding-3-small's
dimension) pending the embedding provider decision in the design doc's Open
Questions; changing it later is a migration like any other.
"""

from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None

GRAPH = "echo_memory"
EMBEDDING_DIM = 1536


def prop(key: str) -> str:
    return f"(properties ->> '\"{key}\"'::agtype)"


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS age")
    op.execute("LOAD 'age'")
    op.execute('SET search_path = ag_catalog, "$user", public')

    op.execute(f"""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM ag_graph WHERE name = '{GRAPH}') THEN
                PERFORM create_graph('{GRAPH}');
            END IF;
        END $$;
    """)
    op.execute(f"SELECT create_vlabel('{GRAPH}', 'Node')")
    op.execute(f"SELECT create_elabel('{GRAPH}', 'FACT')")

    # Node: id (business key), name, type, group_id, aliases
    op.execute(f'CREATE INDEX node_id_idx ON {GRAPH}."Node" ({prop("id")})')
    op.execute(f'CREATE INDEX node_group_idx ON {GRAPH}."Node" ({prop("group_id")})')

    # Edge (label FACT): relation_type, fact, confidence, t_valid, t_invalid,
    # provenance, group_id (no causal_hint in v1a, added via migration in v1b)
    op.execute(f'CREATE INDEX fact_group_idx ON {GRAPH}."FACT" ({prop("group_id")})')
    op.execute(
        f'CREATE INDEX fact_group_start_idx ON {GRAPH}."FACT" '
        f'(({prop("group_id")}), start_id)'
    )
    op.execute(
        f'CREATE INDEX fact_group_end_idx ON {GRAPH}."FACT" '
        f'(({prop("group_id")}), end_id)'
    )
    op.execute(
        f'CREATE INDEX fact_group_validity_idx ON {GRAPH}."FACT" '
        f'(({prop("group_id")}), ({prop("t_valid")}), ({prop("t_invalid")}))'
    )
    op.execute(
        f'CREATE INDEX fact_text_idx ON {GRAPH}."FACT" '
        f"USING GIN (to_tsvector('english', {prop('fact')}))"
    )

    # `SET search_path` above puts ag_catalog first, so everything from here
    # down must be schema-qualified as public.* or it silently lands in
    # ag_catalog instead (caught during PR1's own testing).
    op.execute("""
        CREATE TYPE public.audit_mutation_type AS ENUM (
            'created', 'invalidated', 'fact_superseded', 'entity_resolved'
        )
    """)
    op.execute("""
        CREATE TABLE public.audit_entry (
            id BIGSERIAL PRIMARY KEY,
            "timestamp" TIMESTAMPTZ NOT NULL DEFAULT now(),
            mutation_type public.audit_mutation_type NOT NULL,
            affected_edge_ids graphid[],
            affected_node_id graphid,
            before_fact TEXT,
            after_fact TEXT,
            session_id TEXT NOT NULL,
            summary TEXT NOT NULL,
            resolution_detail TEXT,
            group_id TEXT NOT NULL
        )
    """)
    op.execute(
        'CREATE INDEX audit_entry_group_idx ON public.audit_entry (group_id, "timestamp")'
    )

    op.execute(f"""
        CREATE TABLE public.fact_embedding (
            edge_id graphid PRIMARY KEY,
            group_id TEXT NOT NULL,
            embedding vector({EMBEDDING_DIM}) NOT NULL
        )
    """)
    op.execute("CREATE INDEX fact_embedding_group_idx ON public.fact_embedding (group_id)")
    op.execute(
        "CREATE INDEX fact_embedding_hnsw_idx ON public.fact_embedding "
        "USING hnsw (embedding vector_cosine_ops)"
    )

    op.execute(f"""
        CREATE TABLE public.node_embedding (
            node_id graphid PRIMARY KEY,
            group_id TEXT NOT NULL,
            embedding vector({EMBEDDING_DIM}) NOT NULL
        )
    """)
    op.execute("CREATE INDEX node_embedding_group_idx ON public.node_embedding (group_id)")
    op.execute(
        "CREATE INDEX node_embedding_hnsw_idx ON public.node_embedding "
        "USING hnsw (embedding vector_cosine_ops)"
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS public.node_embedding")
    op.execute("DROP TABLE IF EXISTS public.fact_embedding")
    op.execute("DROP TABLE IF EXISTS public.audit_entry")
    op.execute("DROP TYPE IF EXISTS public.audit_mutation_type")
    op.execute("LOAD 'age'")
    op.execute('SET search_path = ag_catalog, "$user", public')
    op.execute(f"SELECT drop_graph('{GRAPH}', true)")
